// <auto-generated />
using CodingChemistry;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodingChemistry.Migrations
{
    [DbContext(typeof(PeriodicTableDataBase))]
    [Migration("20231014151623_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("CodingChemistry.Element", b =>
                {
                    b.Property<int>("AtomicNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("AtomicNumber");

                    b.ToTable("elements");
                });
#pragma warning restore 612, 618
        }
    }
}
